version: "3"
services:
  server:
    build: ./server
    environment:
      - PORT=80
    depends_on:
      - redis
  redis:
    image: redis
  lb:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./lb.conf:/etc/nginx/conf.d/default.conf
    links:
      - "server:web"
